# Support Vector Classifier

In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red.csv

In [ ]:
data = pd.read_csv('winequality-red.csv')
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [ ]:
data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [ ]:
data.shape

(1599, 12)

In [ ]:
data.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
new_data=scaler.fit_transform(data.drop(labels=['quality'],axis=1))

In [ ]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
columns = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
           'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
           'pH', 'sulphates', 'alcohol']

In [ ]:
new_df = pd.DataFrame(data = new_data, columns=columns)
new_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,0.872638,0.624363,0.028261,-0.719933,0.128950,-0.584777
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,-0.083669,0.229047,0.134264,-0.331177,-0.048089,-0.584777
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,0.107592,0.411500,0.664277,-0.979104,-0.461180,-0.584777
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,-0.466193,-0.379133,0.558274,1.288643,-0.579207,-0.960246

In [ ]:
x=new_df
y=data['quality']

In [ ]:
from  sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2, random_state=33)

In [ ]:
from sklearn.svm import SVC
model=SVC()
model.fit(train_x,train_y)

SVC()

In [ ]:
model.predict(test_x)

array([5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 7,
       5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 7, 6, 5, 6, 5, 5, 5, 5, 6,
       6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 5, 7, 6,
       5, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 7, 6, 6, 6, 6, 7, 5, 5, 6, 7, 6, 6,
       5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 7,
       6, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 7, 6, 5,
       5, 6, 7, 6, 7, 6, 5, 5, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 5, 5, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 7, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 7, 6, 6, 6, 5, 6,
       6, 6, 6, 6, 7, 5, 5, 7, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 7, 5, 6, 5,
       5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 5, 5, 5, 5, 7, 5, 6, 5, 5, 6, 6, 5,
       6, 5, 6, 6, 5, 7, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6,
       6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y,model.predict(test_x))

0.625

Implementing Grid Search

In [ ]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,50,100,500],'gamma':[1,0.5,0.1,0.01,0.001]}
grid= GridSearchCV(SVC(),param_grid, verbose=3, n_jobs=-1)
grid.fit(train_x,train_y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 50, 100, 500],
                         'gamma': [1, 0.5, 0.1, 0.01, 0.001]},
             verbose=3)

In [ ]:
grid.best_params_

{'C': 10, 'gamma': 0.5}

In [ ]:
model_new=SVC(C=10, gamma=1)
model_new.fit(train_x,train_y)

SVC(C=10, gamma=1)

In [ ]:
accuracy_score(test_y,model_new.predict(test_x))

0.640625

### Support Vector Regressor

In [1]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Admission_Prediction.csv to Admission_Prediction.csv

In [3]:
df = pd.read_csv('Admission_Prediction.csv')
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337.0,118.0,4.0,4.5,4.5,9.65,1,0.92
1,2,324.0,107.0,4.0,4.0,4.5,8.87,1,0.76
2,3,NaN,104.0,3.0,3.0,3.5,8.00,1,0.72
3,4,322.0,110.0,3.0,3.5,2.5,8.67,1,0.80
4,5,314.0,103.0,2.0,2.0,3.0,8.21,0,0.65

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         500 non-null    int64
 1   GRE Score          485 non-null    float64
 2   TOEFL Score        490 non-null    float64
 3   University Rating  485 non-null    float64
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64
 8   Chance of Admit    500 non-null    float64
dtypes: float64(7), int64(2)
memory usage: 35.3 KB

In [5]:
df.isna().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [6]:
df.isna().sum().sum()

40

In [7]:
df['GRE Score'].fillna(df['GRE Score'].mean(),inplace=True)
df['TOEFL Score'].fillna(df['TOEFL Score'].mean(),inplace=True)
df['University Rating'].fillna(df['University Rating'].mode()[0],inplace=True)

In [8]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [9]:
x=df.drop(['Chance of Admit','Serial No.'],axis=1)
y=df['Chance of Admit']
columns=x.columns

In [10]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.20, random_state=97)

In [11]:
from sklearn.svm import SVR
svr= SVR(C=10)
svr.fit(train_x, train_y)

SVR(C=10)

In [12]:
from sklearn.metrics import r2_score
score= r2_score(test_y,svr.predict(test_x))
score

0.7608026212904746

Implementing Grid Search

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid={'C':[0.1,1,10,50,100,500],'gamma':[1,0.5,0.1,0.01,0.001] }
grid= GridSearchCV(SVR(),param_grid, verbose=3)

In [14]:
grid.fit(train_x,train_y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END ....................C=0.1, gamma=1;, score=0.091 total time=   0.0s
[CV 2/5] END ....................C=0.1, gamma=1;, score=0.126 total time=   0.0s
[CV 3/5] END ....................C=0.1, gamma=1;, score=0.109 total time=   0.0s
[CV 4/5] END ....................C=0.1, gamma=1;, score=0.113 total time=   0.0s
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.153 total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.5;, score=0.223 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.5;, score=0.279 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.5;, score=0.238 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.5;, score=0.283 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.5;, score=0.314 total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.1;, score=0.545 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.592 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.548 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.521 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.573 total time=   0.0s
[CV 1/5] END .................C=0.1, gamma=0.01;, score=0.700 total time=   0.0s
[CV 2/5] END .................C=0.1, gamma=0.01;, score=0.665 total time=   0.0s
[CV 3/5] END .................C=0.1, gamma=0.01;, score=0.735 total time=   0.0s
[CV 4/5] END .................C=0.1, gamma=0.01;, score=0.620 total time=   0.0s
[CV 5/5] END .................C=0.1, gamma=0.01;, score=0.713 total time=   0.0s
[CV 1/5] END ................C=0.1, gamma=0.001;, score=0.678 total time=   0.0s
[CV 2/5] END ................C=0.1, gamma=0.001;, score=0.677 total time=   0.0s
[CV 3/5] END ................C=0.1, gamma=0.001;, score=0.718 total time=   0.0s
[CV 4/5] END ................C=0.1, gamma=0.001;, score=0.609 total time=   0.0s
[CV 5/5] END ................C=0.1, gamma=0.001;, score=0.700 total time=   0.0s
[CV 1/5] END ......................C=1, gamma=1;, score=0.100 total time=   0.0s
[CV 2/5] END ......................C=1, gamma=1;, score=0.148 total time=   0.0s
[CV 3/5] END ......................C=1, gamma=1;, score=0.123 total time=   0.0s
[CV 4/5] END ......................C=1, gamma=1;, score=0.141 total time=   0.0s
[CV 5/5] END ......................C=1, gamma=1;, score=0.172 total time=   0.0s
[CV 1/5] END ....................C=1, gamma=0.5;, score=0.231 total time=   0.0s
[CV 2/5] END ....................C=1, gamma=0.5;, score=0.316 total time=   0.0s
[CV 3/5] END ....................C=1, gamma=0.5;, score=0.250 total time=   0.0s
[CV 4/5] END ....................C=1, gamma=0.5;, score=0.311 total time=   0.0s
[CV 5/5] END ....................C=1, gamma=0.5;, score=0.330 total time=   0.0s
[CV 1/5] END ....................C=1, gamma=0.1;, score=0.503 total time=   0.0s
[CV 2/5] END ....................C=1, gamma=0.1;, score=0.615 total time=   0.0s
[CV 3/5] END ....................C=1, gamma=0.1;, score=0.505 total time=   0.0s
[CV 4/5] END ....................C=1, gamma=0.1;, score=0.524 total time=   0.0s
[CV 5/5] END ....................C=1, gamma=0.1;, score=0.547 total time=   0.0s
[CV 1/5] END ...................C=1, gamma=0.01;, score=0.708 total time=   0.0s
[CV 2/5] END ...................C=1, gamma=0.01;, score=0.698 total time=   0.0s
[CV 3/5] END ...................C=1, gamma=0.01;, score=0.717 total time=   0.0s
[CV 4/5] END ...................C=1, gamma=0.01;, score=0.651 total time=   0.0s
[CV 5/5] END ...................C=1, gamma=0.01;, score=0.722 total time=   0.0s
[CV 1/5] END ..................C=1, gamma=0.001;, score=0.739 total time=   0.0s
[CV 2/5] END ..................C=1, gamma=0.001;, score=0.719 total time=   0.0s
[CV 3/5] END ..................C=1, gamma=0.001;, score=0.753 total time=   0.0s
[CV 4/5] END ..................C=1, gamma=0.001;, score=0.650 total time=   0.0s
[CV 5/5] END ..................C=1, gamma=0.001;, score=0.745 total time=   0.0s
[CV 1/5] END .....................C=10, gamma=1;, score=0.100 total time=   0.0s
[CV 2/5] END .....................C=10, gamma=1;, score=0.148 total time=   0.0s
[CV 3/5] END .....................C=10, gamma=1;, score=0.123 total time=   0.0s
[CV 4/5] END .....................C=10, gamma=1;, score=0.141 total time=   0.0s
[CV 5/5] END .....................C=10, gamma=1;, score=0.172 total time=   0.0s
[CV 1/5] END ...................C=10, gamma=0.5;, score=0.231 total time=   0.0s
[CV 2/5] END ...................C=10, gamma=0.5;, score=0.316 total time=   0.0s
[CV 3/5] END ...................C=10, gamma=0.5;, score=0.250 total time=   0.0s
[CV 4/5] END ...................C=10, gamma=0.5;, score=0.311 total time=   0.0s
[CV 5/5] END ...................C=10, gamma=0.5;, score=0.330 total time=   0.0s
[CV 1/5] END ...................C=10, gamma=0.1;, score=0.503 total time=   0.0s
[CV 2/5] END ...................C=10, gamma=0.1;, score=0.611 total time=   0.0s
[CV 3/5] END ...................C=10, gamma=0.1;, score=0.507 total time=   0.0s
[CV 4/5] END ...................C=10, gamma=0.1;, score=0.524 total time=   0.0s
[CV 5/5] END ...................C=10, gamma=0.1;, score=0.531 total time=   0.0s
[CV 1/5] END ..................C=10, gamma=0.01;, score=0.701 total time=   0.0s
[CV 2/5] END ..................C=10, gamma=0.01;, score=0.718 total time=   0.0s
[CV 3/5] END ..................C=10, gamma=0.01;, score=0.740 total time=   0.0s
[CV 4/5] END ..................C=10, gamma=0.01;, score=0.618 total time=   0.0s
[CV 5/5] END ..................C=10, gamma=0.01;, score=0.700 total time=   0.0s
[CV 1/5] END .................C=10, gamma=0.001;, score=0.745 total time=   0.0s
[CV 2/5] END .................C=10, gamma=0.001;, score=0.712 total time=   0.0s
[CV 3/5] END .................C=10, gamma=0.001;, score=0.769 total time=   0.0s
[CV 4/5] END .................C=10, gamma=0.001;, score=0.676 total time=   0.0s
[CV 5/5] END .................C=10, gamma=0.001;, score=0.762 total time=   0.0s
[CV 1/5] END .....................C=50, gamma=1;, score=0.100 total time=   0.0s
[CV 2/5] END .....................C=50, gamma=1;, score=0.148 total time=   0.0s
[CV 3/5] END .....................C=50, gamma=1;, score=0.123 total time=   0.0s
[CV 4/5] END .....................C=50, gamma=1;, score=0.141 total time=   0.0s
[CV 5/5] END .....................C=50, gamma=1;, score=0.172 total time=   0.0s
[CV 1/5] END ...................C=50, gamma=0.5;, score=0.231 total time=   0.0s
[CV 2/5] END ...................C=50, gamma=0.5;, score=0.316 total time=   0.0s
[CV 3/5] END ...................C=50, gamma=0.5;, score=0.250 total time=   0.0s
[CV 4/5] END ...................C=50, gamma=0.5;, score=0.311 total time=   0.0s
[CV 5/5] END ...................C=50, gamma=0.5;, score=0.330 total time=   0.0s
[CV 1/5] END ...................C=50, gamma=0.1;, score=0.503 total time=   0.0s
[CV 2/5] END ...................C=50, gamma=0.1;, score=0.611 total time=   0.0s
[CV 3/5] END ...................C=50, gamma=0.1;, score=0.507 total time=   0.0s
[CV 4/5] END ...................C=50, gamma=0.1;, score=0.524 total time=   0.0s
[CV 5/5] END ...................C=50, gamma=0.1;, score=0.531 total time=   0.0s
[CV 1/5] END ..................C=50, gamma=0.01;, score=0.619 total time=   0.0s
[CV 2/5] END ..................C=50, gamma=0.01;, score=0.666 total time=   0.0s
[CV 3/5] END ..................C=50, gamma=0.01;, score=0.645 total time=   0.0s
[CV 4/5] END ..................C=50, gamma=0.01;, score=0.592 total time=   0.0s
[CV 5/5] END ..................C=50, gamma=0.01;, score=0.684 total time=   0.0s
[CV 1/5] END .................C=50, gamma=0.001;, score=0.753 total time=   0.0s
[CV 2/5] END .................C=50, gamma=0.001;, score=0.721 total time=   0.0s
[CV 3/5] END .................C=50, gamma=0.001;, score=0.759 total time=   0.0s
[CV 4/5] END .................C=50, gamma=0.001;, score=0.694 total time=   0.0s
[CV 5/5] END .................C=50, gamma=0.001;, score=0.771 total time=   0.0s
[CV 1/5] END ....................C=100, gamma=1;, score=0.100 total time=   0.0s
[CV 2/5] END ....................C=100, gamma=1;, score=0.148 total time=   0.0s
[CV 3/5] END ....................C=100, gamma=1;, score=0.123 total time=   0.0s
[CV 4/5] END ....................C=100, gamma=1;, score=0.141 total time=   0.0s
[CV 5/5] END ....................C=100, gamma=1;, score=0.172 total time=   0.0s
[CV 1/5] END ..................C=100, gamma=0.5;, score=0.231 total time=   0.0s
[CV 2/5] END ..................C=100, gamma=0.5;, score=0.316 total time=   0.0s
[CV 3/5] END ..................C=100, gamma=0.5;, score=0.250 total time=   0.0s
[CV 4/5] END ..................C=100, gamma=0.5;, score=0.311 total time=   0.0s
[CV 5/5] END ..................C=100, gamma=0.5;, score=0.330 total time=   0.0s
[CV 1/5] END ..................C=100, gamma=0.1;, score=0.503 total time=   0.0s
[CV 2/5] END ..................C=100, gamma=0.1;, score=0.611 total time=   0.0s
[CV 3/5] END ..................C=100, gamma=0.1;, score=0.507 total time=   0.0s
[CV 4/5] END ..................C=100, gamma=0.1;, score=0.524 total time=   0.0s
[CV 5/5] END ..................C=100, gamma=0.1;, score=0.531 total time=   0.0s
[CV 1/5] END .................C=100, gamma=0.01;, score=0.585 total time=   0.0s
[CV 2/5] END .................C=100, gamma=0.01;, score=0.644 total time=   0.0s
[CV 3/5] END .................C=100, gamma=0.01;, score=0.632 total time=   0.0s
[CV 4/5] END .................C=100, gamma=0.01;, score=0.592 total time=   0.0s
[CV 5/5] END .................C=100, gamma=0.01;, score=0.627 total time=   0.0s
[CV 1/5] END ................C=100, gamma=0.001;, score=0.741 total time=   0.0s
[CV 2/5] END ................C=100, gamma=0.001;, score=0.722 total time=   0.0s
[CV 3/5] END ................C=100, gamma=0.001;, score=0.758 total time=   0.0s
[CV 4/5] END ................C=100, gamma=0.001;, score=0.705 total time=   0.0s
[CV 5/5] END ................C=100, gamma=0.001;, score=0.781 total time=   0.0s
[CV 1/5] END ....................C=500, gamma=1;, score=0.100 total time=   0.0s
[CV 2/5] END ....................C=500, gamma=1;, score=0.148 total time=   0.0s
[CV 3/5] END ....................C=500, gamma=1;, score=0.123 total time=   0.0s
[CV 4/5] END ....................C=500, gamma=1;, score=0.141 total time=   0.0s
[CV 5/5] END ....................C=500, gamma=1;, score=0.172 total time=   0.0s
[CV 1/5] END ..................C=500, gamma=0.5;, score=0.231 total time=   0.0s
[CV 2/5] END ..................C=500, gamma=0.5;, score=0.316 total time=   0.0s
[CV 3/5] END ..................C=500, gamma=0.5;, score=0.250 total time=   0.0s
[CV 4/5] END ..................C=500, gamma=0.5;, score=0.311 total time=   0.0s
[CV 5/5] END ..................C=500, gamma=0.5;, score=0.330 total time=   0.0s
[CV 1/5] END ..................C=500, gamma=0.1;, score=0.503 total time=   0.0s
[CV 2/5] END ..................C=500, gamma=0.1;, score=0.611 total time=   0.0s
[CV 3/5] END ..................C=500, gamma=0.1;, score=0.507 total time=   0.0s
[CV 4/5] END ..................C=500, gamma=0.1;, score=0.524 total time=   0.0s
[CV 5/5] END ..................C=500, gamma=0.1;, score=0.531 total time=   0.0s
[CV 1/5] END .................C=500, gamma=0.01;, score=0.556 total time=   0.0s
[CV 2/5] END .................C=500, gamma=0.01;, score=0.535 total time=   0.0s
[CV 3/5] END .................C=500, gamma=0.01;, score=0.564 total time=   0.0s
[CV 4/5] END .................C=500, gamma=0.01;, score=0.592 total time=   0.0s
[CV 5/5] END .................C=500, gamma=0.01;, score=0.431 total time=   0.0s
[CV 1/5] END ................C=500, gamma=0.001;, score=0.728 total time=   0.0s
[CV 2/5] END ................C=500, gamma=0.001;, score=0.717 total time=   0.0s
[CV 3/5] END ................C=500, gamma=0.001;, score=0.778 total time=   0.0s
[CV 4/5] END ................C=500, gamma=0.001;, score=0.715 total time=   0.0s
[CV 5/5] END ................C=500, gamma=0.001;, score=0.787 total time=   0.1s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 50, 100, 500],
                         'gamma': [1, 0.5, 0.1, 0.01, 0.001]},
             verbose=3)

In [15]:
grid.best_estimator_

SVR(C=500, gamma=0.001)

In [16]:
svr_new=SVR(C=50, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.001, kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [17]:
svr_new.fit(train_x, train_y)

SVR(C=50, gamma=0.001)

In [18]:
score_new= r2_score(test_y,svr_new.predict(test_x))
score_new

0.7822883538162705

In [19]:
svr_old=SVR(C=500, gamma=0.001)

In [20]:
svr_old.fit(train_x, train_y)

SVR(C=500, gamma=0.001)

In [21]:
score_old= r2_score(test_y,svr_old.predict(test_x))
score_old

0.7961122473766142